import type { Metadata } from 'next';
import { Inter, Manrope } from 'next/font/google';
import './globals.css';
import QueryProvider from '@/shared/providers/QueryProvider';
import { Toaster } from '@/shared/components/ui/sonner';
import ModalsProvider from '@/features/modal/providers/ModalsProvider';
import LoaderProvider from '@/features/loader/providers/LoaderProvider';
import MainProvider from '@/shared/providers/MainProvider';
import SmoothScroll from '@/shared/components/SmoothScroll';

const interFont = Inter({
   subsets: ['latin', 'cyrillic'],
});
const manrope = Manrope({
   variable: '--font-manrope',
   subsets: ['latin', 'cyrillic'],
   weight: ['800'],
});

export const metadata: Metadata = {
   title: 'Social',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={`${manrope.variable} ${interFont.className}  bg-neutralWhite-200 antialiased`}
         >
            <MainProvider>
               <SmoothScroll />
               <div className="max-w-7xl mx-auto px-6 box-content pb-10">
                  {children}
               </div>
               <Toaster />
            </MainProvider>
         </body>
      </html>
   );
}
