import type { Metadata } from 'next';
import { Inter, Manrope } from 'next/font/google';
import './globals.css';
import QueryProvider from '@/providers/QueryProvider';
import { Toaster } from '@/components/ui/sonner';

const interFont = Inter({
   variable: '--font-inter',
   subsets: ['latin', 'cyrillic'],
});
const manrope = Manrope({
   variable: '--font-manrope',
   subsets: ['latin', 'cyrillic'],
   weight: ['800'],
});

export const metadata: Metadata = {
   title: 'Social',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={`${interFont.variable} ${manrope.variable} bg-neutralWhite-200 antialiased`}
         >
            <QueryProvider>
               <div className="max-w-7xl mx-auto px-">{children}</div>
               <Toaster />
            </QueryProvider>
         </body>
      </html>
   );
}
